package modelo;
// Generated 20-may-2018 14:08:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java.
 */
public class Categoria implements java.io.Serializable {

    /**
     * Variable que representa el id de la categoria.
     */
     private int idCategoria;
     /**
      * Variable que representa el nombre de la categoria.
      */
     private String nombre;
     /**
      * Conjunto de las preguntas de la categoria.
      */
     private Set preguntas = new HashSet(0);

     /**
      * Metodo constructor de una categoria.
      */
    public Categoria() {
    }

    /**
     * Constructor de la clase categoria.
     * @param idCategoriaAux el id de la categoria.
     * @param nombreAux el nombre de la categoria.
     */
    public Categoria(final int idCategoriaAux, final String nombreAux) {
        this.idCategoria = idCategoriaAux;
        this.nombre = nombreAux;
    }

    /**
     * Constructor de la clase categoria.
     * @param idCategoriaAux id de la categoria.
     * @param nombreAux nombre de la categoria.
     * @param preguntasAux preguntas de la categoria.
     */
    public Categoria(final int idCategoriaAux,
                    final String nombreAux, final Set preguntasAux) {
       this.idCategoria = idCategoriaAux;
       this.nombre = nombreAux;
       this.preguntas = preguntasAux;
    }

    /**
     * Metodo que regresa el id de la categoria.
     * @return el id de la cateogria
     */
    public int getIdCategoria() {
        return this.idCategoria;
    }
    /**
    * Metodo de la clase categoria.
    *@param idCategoriaAux atributo.
    */
    public void setIdCategoria(final int idCategoriaAux) {
        this.idCategoria = idCategoriaAux;
    }
    /**
    * Metodo de la clase categoria.
    *@return atributo.
    */
    public String getNombre() {
        return this.nombre;
    }
    /**
    * Metodo de la clase categoria.
    *@param nombreAux atributo.
    */
    public void setNombre(final String nombreAux) {
        this.nombre = nombreAux;
    }
    /**
    * Metodo de la clase categoria.
    *@return atributo.
    */
    public Set getPreguntas() {
        return this.preguntas;
    }
    /**
    * Metodo de la clase categoria.
    *@param preguntasAux atributo.
    */
    public void setPreguntas(final Set preguntasAux) {
        this.preguntas = preguntasAux;
    }
}


