package modelo;
// Generated 20-may-2018 14:08:49 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pregunta generated by hbm2java.
 */
public class Pregunta  implements java.io.Serializable {

    /**
    * Variable de la clase.
    */
     private int idPregunta;
    /**
    * Variable de la clase.
    */
     private String contenido;
    /**
    * Variable de la clase.
    */
     private String categoria;
    /**
    * Variable de la clase.
    */
     private String descripcion;
    /**
    * Variable de la clase.
    */
     private Date fechaCreacion;
    /**
    * Variable de la clase.
    */
     private Set categorias = new HashSet(0);
    /**
    * Variable de la clase.
    */
     private Set respuestas = new HashSet(0);
    /**
    * Variable de la clase.
    */
     private Set usuarios = new HashSet(0);
    /**
    * Variable de la clase.
    */

    /**
    * Constructor de la clase pregunta.
    */
    public Pregunta() {
    }

    /**
    * Constructor de la clase pregunta.
    */
    public Pregunta(int idPregunta, String contenido, String categoria, String descripcion) {
        this.idPregunta = idPregunta;
        this.contenido = contenido;
        this.categoria = categoria;
        this.descripcion = descripcion;
    }
    /**
    * Constructor de la clase pregunta.
    */
    public Pregunta(int idPregunta, String contenido, String categoria, String descripcion, Date fechaCreacion, Set categorias, Set respuestas, Set usuarios) {
       this.idPregunta = idPregunta;
       this.contenido = contenido;
       this.categoria = categoria;
       this.descripcion = descripcion;
       this.fechaCreacion = fechaCreacion;
       this.categorias = categorias;
       this.respuestas = respuestas;
       this.usuarios = usuarios;
    }
    /**
    *    Metodo de la clase pregunta.
    *@return atributo.
    */
    public int getIdPregunta() {
        return this.idPregunta;
    }
    /**
    * Metodo de la clase pregunta.
    *@param idPreguntaAux variable.
    */
    public void setIdPregunta(final int idPreguntaAux) {
        this.idPregunta = idPreguntaAux;
    }
    /**
    * Metodo de la clase pregunta.
    *@return atributo.
    */
    public String getContenido() {
        return this.contenido;
    }
    /**
    * Metodo de la clase pregunta.
    *@param contenidoAux variable.
    */
    public void setContenido(final String contenidoAux) {
        this.contenido = contenidoAux;
    }
    /**
    * Metodo de la clase pregunta.
    *@return atributo.
    */
    public String getCategoria() {
        return this.categoria;
    }
    /**
    * Metodo de la clase pregunta.
    *@param categoriaAux variablr
    */
    public void setCategoria(final String categoriaAux) {
        this.categoria = categoriaAux;
    }
    /**
    * Metodo de la clase pregunta.
    *@return atributo.
    */
    public String getDescripcion() {
        return this.descripcion;
    }
    /**
    * Metodo de la clase pregunta.
    *@param descripcionAux variable.
    */
    public void setDescripcion(final String descripcionAux) {
        this.descripcion = descripcionAux;
    }
    /**
    * Metodo de la clase pregunta.
    *@return atributo.
    */
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    /**
    * Metodo de la clase pregunta.
    *@param fechaCreacionAux variable
    */
    public void setFechaCreacion(final Date fechaCreacionAux) {
        this.fechaCreacion = fechaCreacionAux;
    }
    /**
    * Metodo de la clase pregunta.
    *@return atributo.
    */
    public Set getCategorias() {
        return this.categorias;
    }
    /**
    * Metodo de la clase pregunta.
    *@param categoriasAux variable.
    */
    public void setCategorias(final Set categoriasAux) {
        this.categorias = categoriasAux;
    }
    /**
    * Metodo de la clase pregunta.
    *@return atributo.
    */
    public Set getRespuestas() {
        return this.respuestas;
    }
    /**
    * Metodo de la clase pregunta.
    *@param respuestasAux variable.
    */
    public void setRespuestas(final Set respuestasAux) {
        this.respuestas = respuestasAux;
    }
    /**
    * Metodo de la clase pregunta.
    *@return atributo.
    */
    public Set getUsuarios() {
        return this.usuarios;
    }
    /**
    * Metodo de la clase pregunta.
    *@param usuariosAux variable
    */
    public void setUsuarios(final Set usuariosAux) {
        this.usuarios = usuariosAux;
    }

    public void imprime() {
        System.out.println(this.categoria);
        System.out.println(this.descripcion);
        System.out.println(this.contenido);
        
    }



}


