package modelo;
// Generated 16-abr-2018 21:37:46 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pregunta generated by hbm2java
 */
public class Pregunta  implements java.io.Serializable {


     private int idPregunta;
     private String contenido;
     private String categoria;
     private String descripcion;
     private Date fechaCreacion;
     private Set categorias = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Pregunta() {
    }

	
    public Pregunta(int idPregunta, String contenido, String categoria, String descripcion) {
        this.idPregunta = idPregunta;
        this.contenido = contenido;
        this.categoria = categoria;
        this.descripcion = descripcion;
    }
    public Pregunta(int idPregunta, String contenido, String categoria, String descripcion, Date fechaCreacion, Set categorias, Set usuarios) {
       this.idPregunta = idPregunta;
       this.contenido = contenido;
       this.categoria = categoria;
       this.descripcion = descripcion;
       this.fechaCreacion = fechaCreacion;
       this.categorias = categorias;
       this.usuarios = usuarios;
    }
   
    public int getIdPregunta() {
        return this.idPregunta;
    }
    
    public void setIdPregunta(int idPregunta) {
        this.idPregunta = idPregunta;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Set getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Set categorias) {
        this.categorias = categorias;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


