package modelo;
// Generated 20-may-2018 14:08:49 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Respuesta generated by hbm2java.
 */
public class Respuesta  implements java.io.Serializable {

    /**
    *Atributo de la clase respuesta.
    */
    private int idRespuesta;
    /**
    *Atributo de la clase respuesta.
    */
    private String descripcion;
    /**
    *Atributo de la clase respuesta.
    */
    private Date fechaCreacion;
    /**
    *Atributo de la clase respuesta.
    */
    private Set preguntas = new HashSet(0);

    /**
    *Metodo de la clase respuesta.
    *@
    */
    public Respuesta() {
    }

    /**
    *Metodo de la clase respuesta.
    *@param idRespuestaAux
    */
    public Respuesta(final int idRespuestaAux) {
        this.idRespuesta = idRespuestaAux;
    }
    /**
    *Metodo de la clase respuesta.
    */
    public Respuesta(int idRespuesta, String descripcion, Date fechaCreacion, Set preguntas) {
       this.idRespuesta = idRespuesta;
       this.descripcion = descripcion;
       this.fechaCreacion = fechaCreacion;
       this.preguntas = preguntas;
    }
    /**
    *Metodo de la clase respuesta.
    *@return atributo
    */
    public int getIdRespuesta() {
        return this.idRespuesta;
    }
    /**
    *Metodo de la clase respuesta.
    *@param idRespuestaAux variable.
    */
    public void setIdRespuesta(final int idRespuestaAux) {
        this.idRespuesta = idRespuestaAux;
    }
    /**
    *Metodo de la clase respuesta.
    *@return atributo
    */
    public String getDescripcion() {
        return this.descripcion;
    }
    /**
    *Metodo de la clase respuesta.
    *@param descripcionAux variable.
    */
    public void setDescripcion(final String descripcionAux) {
        this.descripcion = descripcionAux;
    }
    /**
    *Metodo de la clase respuesta.
    *@return atributo
    */
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    /**
    *Metodo de la clase respuesta.
    *@param fechaCreacionAux variable.
    */
    public void setFechaCreacion(final Date fechaCreacionAux) {
        this.fechaCreacion = fechaCreacionAux;
    }
    /**
    *Metodo de la clase respuesta.
    *@return atributo
    */
    public Set getPreguntas() {
        return this.preguntas;
    }
    /**
    *Metodo de la clase respuesta.
    *@param preguntasAux variable.
    */
    public void setPreguntas(final Set preguntasAux) {
        this.preguntas = preguntasAux;
    }




}


