package modelo;
// Generated 20-may-2018 14:08:49 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private String nombreUsuario;
     private String nombre;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String correoElectronico;
     private String contrasena;
     private Date fechaDeNacimiento;
     private String carrera;
     private Date fechaIngreso;
     private boolean activo;
     private boolean permisosAdmin;
     private byte[] imagenPerfil;
     private boolean confirmado;
     private Set preguntas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int idUsuario, String nombreUsuario, String nombre, String apellidoPaterno, String apellidoMaterno, String correoElectronico, String contrasena, boolean activo, boolean permisosAdmin, boolean confirmado) {
        this.idUsuario = idUsuario;
        this.nombreUsuario = nombreUsuario;
        this.nombre = nombre;
        this.apellidoPaterno = apellidoPaterno;
        this.apellidoMaterno = apellidoMaterno;
        this.correoElectronico = correoElectronico;
        this.contrasena = contrasena;
        this.activo = activo;
        this.permisosAdmin = permisosAdmin;
        this.confirmado = confirmado;
    }
    public Usuario(int idUsuario, String nombreUsuario, String nombre, String apellidoPaterno, String apellidoMaterno, String correoElectronico, String contrasena, Date fechaDeNacimiento, String carrera, Date fechaIngreso, boolean activo, boolean permisosAdmin, byte[] imagenPerfil, boolean confirmado, Set preguntas) {
       this.idUsuario = idUsuario;
       this.nombreUsuario = nombreUsuario;
       this.nombre = nombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.correoElectronico = correoElectronico;
       this.contrasena = contrasena;
       this.fechaDeNacimiento = fechaDeNacimiento;
       this.carrera = carrera;
       this.fechaIngreso = fechaIngreso;
       this.activo = activo;
       this.permisosAdmin = permisosAdmin;
       this.imagenPerfil = imagenPerfil;
       this.confirmado = confirmado;
       this.preguntas = preguntas;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public Date getFechaDeNacimiento() {
        return this.fechaDeNacimiento;
    }
    
    public void setFechaDeNacimiento(Date fechaDeNacimiento) {
        this.fechaDeNacimiento = fechaDeNacimiento;
    }
    public String getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(String carrera) {
        this.carrera = carrera;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public boolean isPermisosAdmin() {
        return this.permisosAdmin;
    }
    
    public void setPermisosAdmin(boolean permisosAdmin) {
        this.permisosAdmin = permisosAdmin;
    }
    public byte[] getImagenPerfil() {
        return this.imagenPerfil;
    }
    
    public void setImagenPerfil(byte[] imagenPerfil) {
        this.imagenPerfil = imagenPerfil;
    }
    public boolean isConfirmado() {
        return this.confirmado;
    }
    
    public void setConfirmado(boolean confirmado) {
        this.confirmado = confirmado;
    }
    public Set getPreguntas() {
        return this.preguntas;
    }
    
    public void setPreguntas(Set preguntas) {
        this.preguntas = preguntas;
    }

    public void to_String() {
        System.out.println(this.nombre);
        System.out.println(this.nombreUsuario);
        System.out.println(this.apellidoMaterno);
        System.out.println(this.idUsuario);
        System.out.println(this.fechaIngreso);
        System.out.println(this.contrasena);
        System.out.println(this.carrera);
    }


}


