package modelo;
// Generated 20-may-2018 14:08:49 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java.
 */
public class Usuario  implements java.io.Serializable {

    /**
    * Variable que representa un atributo del usuario.
    */
     private int idUsuario;
     /**
     * Variable que representa un atributo del usuario.
     */
     private String nombreUsuario;
     /**
     * Variable que representa un atributo del usuario.
     */
     private String nombre;
     /**
     * Variable que representa un atributo del usuario.
     */
     private String apellidoPaterno;
     /**
     * Variable que representa un atributo del usuario.
     */
     private String apellidoMaterno;
     /**
     * Variable que representa un atributo del usuario.
     */
     private String correoElectronico;
     /**
     * Variable que representa un atributo del usuario.
     */
     private String contrasena;
     /**
     * Variable que representa un atributo del usuario.
     */
     private Date fechaDeNacimiento;
     /**
     * Variable que representa un atributo del usuario.
     */
     private String carrera;
     /**
     * Variable que representa un atributo del usuario.
     */
     private Date fechaIngreso;
     /**
     * Variable que representa un atributo del usuario.
     */
     private boolean activo;
     /**
     * Variable que representa un atributo del usuario.
     */
     private boolean permisosAdmin;
     /**
     * Variable que representa un atributo del usuario.
     */
     private byte[] imagenPerfil;
     /**
     * Variable que representa un atributo del usuario.
     */
     private boolean confirmado;
     /**
     * Variable que representa un atributo del usuario.
     */
     private Set preguntas = new HashSet(0);
     /**
     * Variable que representa un atributo del usuario.
     */

    /**
    * Constructor de la clase usuario.
    */
    public Usuario() {
    }

    /**
    * Constructor de la clase usuario.
    */
    public Usuario(int idUsuario, String nombreUsuario, String nombre, String apellidoPaterno, String apellidoMaterno, String correoElectronico, String contrasena, boolean activo, boolean permisosAdmin, boolean confirmado) {
        this.idUsuario = idUsuario;
        this.nombreUsuario = nombreUsuario;
        this.nombre = nombre;
        this.apellidoPaterno = apellidoPaterno;
        this.apellidoMaterno = apellidoMaterno;
        this.correoElectronico = correoElectronico;
        this.contrasena = contrasena;
        this.activo = activo;
        this.permisosAdmin = permisosAdmin;
        this.confirmado = confirmado;
    }
    /**
    * Constructor de la clase usuario.
    */
    public Usuario(int idUsuario, String nombreUsuario, String nombre, String apellidoPaterno, String apellidoMaterno, String correoElectronico, String contrasena, Date fechaDeNacimiento, String carrera, Date fechaIngreso, boolean activo, boolean permisosAdmin, byte[] imagenPerfil, boolean confirmado, Set preguntas) {
       this.idUsuario = idUsuario;
       this.nombreUsuario = nombreUsuario;
       this.nombre = nombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.correoElectronico = correoElectronico;
       this.contrasena = contrasena;
       this.fechaDeNacimiento = fechaDeNacimiento;
       this.carrera = carrera;
       this.fechaIngreso = fechaIngreso;
       this.activo = activo;
       this.permisosAdmin = permisosAdmin;
       this.imagenPerfil = imagenPerfil;
       this.confirmado = confirmado;
       this.preguntas = preguntas;
    }
    /**
    * Metodo que modifica o regresa un atributo de clase.
    *@return atributo
    */
    public int getIdUsuario() {
        return this.idUsuario;
    }
    /**
    * Metodo que modifica o regresa un atributo de clase.
    *@param idUsuarioAux  variable.
    */
    public void setIdUsuario(final int idUsuarioAux) {
        this.idUsuario = idUsuarioAux;
    }
    /**
    * Metodo que modifica o regresa un atributo de clase.
    *@return atributo
    */
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    /**
    * Metodo que modifica o regresa un atributo de clase.
    *@param nombreUsuarioAux variable.
    */
    public void setNombreUsuario(final String nombreUsuarioAux) {
        this.nombreUsuario = nombreUsuarioAux;
    }
    /**
    * Metodo que modifica o regresa un atributo de clase.
    *@return atributo
    */
    public String getNombre() {
        return this.nombre;
    }
    /**
    * Metodo que modifica o regresa un atributo de clase.
    *@param nombreAux variable.
    */
    public void setNombre(final String nombreAux) {
        this.nombre = nombreAux;
    }
    /**
    * Metodo que modifica o regresa un atributo de clase.
    *@return atributo
    */
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    /**
    * Metodo que modifica o regresa un atributo de clase.
    *@param apellidoPaternoAux variable.
    */
    public void setApellidoPaterno(final String apellidoPaternoAux) {
        this.apellidoPaterno = apellidoPaternoAux;
    }
    /**
    * Metodo que modifica o regresa un atributo de clase.
    *@return atributo
    */
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    /**
    * Metodo que modifica o regresa un atributo de clase.
    *@param apellidoMaternoAux variable.
    */
    public void setApellidoMaterno(final String apellidoMaternoAux) {
        this.apellidoMaterno = apellidoMaternoAux;
    }
    /**
    * Metodo que modifica o regresa un atributo de clase.
    *@return atributo
    */
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    /**
    * Metodo que modifica o regresa un atributo de clase.
    *@param correoElectronicoAux variable.
    */
    public void setCorreoElectronico(final String correoElectronicoAux) {
        this.correoElectronico = correoElectronicoAux;
    }
    /**
    * Metodo que modifica o regresa un atributo de clase.
    *@return atributo
    */
    public String getContrasena() {
        return this.contrasena;
    }
    /**
    * Metodo que modifica o regresa un atributo de clase.
    *@param contrasenaAux variable.
    */
    public void setContrasena(final String contrasenaAux) {
        this.contrasena = contrasenaAux;
    }
    /**
    * Metodo que modifica o regresa un atributo de clase.
    *@return atributo
    */
    public Date getFechaDeNacimiento() {
        return this.fechaDeNacimiento;
    }
    /**
    * Metodo que modifica o regresa un atributo de clase.
    *@param fechaDeNacimientoAux variable.
    */
    public void setFechaDeNacimiento(final Date fechaDeNacimientoAux) {
        this.fechaDeNacimiento = fechaDeNacimientoAux;
    }
    /**
    * Metodo que modifica o regresa un atributo de clase.
    *@return atributo
    */
    public String getCarrera() {
        return this.carrera;
    }
    /**
    * Metodo que modifica o regresa un atributo de clase.
    *@param carreraAux variable.
    */
    public void setCarrera(final String carreraAux) {
        this.carrera = carreraAux;
    }
    /**
    * Metodo que modifica o regresa un atributo de clase.
    *@return atributo
    */
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    /**
    * Metodo que modifica o regresa un atributo de clase.
    *@param fechaIngresoAux variable.
    */
    public void setFechaIngreso(final Date fechaIngresoAux) {
        this.fechaIngreso = fechaIngresoAux;
    }
    /**
    * Metodo que modifica o regresa un atributo de clase.
    *@return atributo
    */
    public boolean isActivo() {
        return this.activo;
    }
    /**
    * Metodo que modifica o regresa un atributo de clase.
    *@param activoAux variable.
    */
    public void setActivo(final boolean activoAux) {
        this.activo = activoAux;
    }
    /**
    * Metodo que modifica o regresa un atributo de clase.
    *@return atributo
    */
    public boolean isPermisosAdmin() {
        return this.permisosAdmin;
    }
    /**
    * Metodo que modifica o regresa un atributo de clase.
    *@param permisosAdminAux variable.
    */
    public void setPermisosAdmin(final boolean permisosAdminAux) {
        this.permisosAdmin = permisosAdminAux;
    }
    /**
    * Metodo que modifica o regresa un atributo de clase.
    *@return atributo
    */
    public byte[] getImagenPerfil() {
        return this.imagenPerfil;
    }
    /**
    * Metodo que modifica o regresa un atributo de clase.
    *@param imagenPerfilAux variable.
    */
    public void setImagenPerfil(final byte[] imagenPerfilAux) {
        this.imagenPerfil = imagenPerfilAux;
    }
    /**
    * Metodo que modifica o regresa un atributo de clase.
    *@return atributo
    */
    public boolean isConfirmado() {
        return this.confirmado;
    }
    /**
    * Metodo que modifica o regresa un atributo de clase.
    *@param confirmadoAux variable.
    */
    public void setConfirmado(final boolean confirmadoAux) {
        this.confirmado = confirmadoAux;
    }
    /**
    * Metodo que modifica o regresa un atributo de clase.
    *@return atributo
    */
    public Set getPreguntas() {
        return this.preguntas;
    }
    /**
    * Metodo que modifica o regresa un atributo de clase.
    *@param preguntasAux variable.
    */
    public void setPreguntas(final Set preguntasAux) {
        this.preguntas = preguntasAux;
    }
    /**
    * Metodo que modifica o regresa un atributo de clase.
    */
    public void to_String() {
        System.out.println(this.nombre);
        System.out.println(this.nombreUsuario);
        System.out.println(this.apellidoMaterno);
        System.out.println(this.idUsuario);
        System.out.println(this.fechaIngreso);
        System.out.println(this.contrasena);
        System.out.println(this.carrera);
    }


}


